# Generated by Django 5.1.5 on 2025-02-03 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_seller',
            field=models.BooleanField(default=True),
        ),
    ]
